version: '3'

services:
  eureka:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka:/app
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
  apigateway:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8765:8080'
    working_dir: /app
    volumes:
      - ./apigateway:/app
    depends_on:
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
  mariadbdev:
    container_name: walmart_mariadb
    restart: always
    image: mariadb
    command: --lower_case_table_names=1
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mywalmartapi'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes:
      - my-datavolume:/var/lib/mariadb
  mainfunctions:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8081:8081'
    working_dir: /app
    volumes:
      - ./mainfunctions:/app
    depends_on:
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
volumes:
  my-datavolume: